# Usar una imagen base de JDK 11
FROM openjdk:17-jre-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo JAR de tu aplicación al contenedor
COPY target/springboot-servicio-gateway-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 8090

# Ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]