spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          servicio-usuarios:
            provider: spring
            client-id: servicio-usuarios
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              - openid
              - profile
              - read
            client-name: servicio-usuarios
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"
